SEApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

base/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerPage, name="register"),

    path('', views.home, name="home"),
    path('message/<str:pk>/', views.message, name="message"),

    path('create-message/', views.createMessage, name="create-message"),
    path('store/', views.store, name="store"),
    path('profile/', views.profile, name="profile"),
    path('leaderboard/', views.leaderboard, name="leaderboard"),
    path('settings/', views.settings, name="settings"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from tkinter import CASCADE
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
# Create your models here.


class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver')
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    pointTotal = models.IntegerField()

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.body[0:50]

class StoreItem(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    cost = models.IntegerField()
    timesPurchased = models.IntegerField(default=0)

    class Meta:
        ordering = ['-timesPurchased']

    def __str__(self):
        return self.name 
class Profile(models.Model):
    profilePic = models.ImageField(null=True, blank=True,default='/images/StoreAssets/SmileAssetRed.png')
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    email = models.EmailField(null=True, blank=True)
    notificationsOn = models.BooleanField(default=True)
    privacyOn = models.BooleanField(default=False)
    pointsToSend = models.IntegerField(default=100)
    pointsReceived = models.IntegerField(default=0)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    lastMessageSent = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-pointsReceived']

    def __str__(self):
        return str(self.user)
        
class PublicProfile(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='+')  
class PurchaseItem(models.Model):
    item = models.ForeignKey(StoreItem, on_delete=models.CASCADE, related_name='+')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    def purchase(item,profile):
        if profile.pointsReceived < item.cost:
                error = "Error not enough points!"
                print("Error not enough points!")
                return False
        profile.pointsReceived = profile.pointsReceived- item.cost
        profile.save()
        item.timesPurchased = item.timesPurchased + 1
        item.save()
        message = "Successfully purchased " + str(item.name) + " for " + str(item.cost)
        print(message)
        return True 
    class Meta:
        ordering = ['-created']

    def __str__(self):
        return str(self.item)

base/forms.py
from tkinter.tix import Form
from django.forms import EmailField, EmailInput, ModelForm
from matplotlib import widgets
from .models import Message, Profile, PublicProfile, PurchaseItem
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['receiver', 'body']


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class SettingsForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['email', 'privacyOn', 'notificationsOn', 'profilePic']

        # widgets = {
        #     'email': EmailInput(attrs={
        #         'style' : 'font-size: 40px'
        #     })
        # }

class PurchaseForm(ModelForm):
    class Meta:
        model = PurchaseItem
        fields = ['item']
class ProfileForm(ModelForm):
    def __init__(self,*args,**kwargs):
        super (ProfileForm,self ).__init__(*args,**kwargs)
        self.fields['profile'].queryset = Profile.objects.filter(privacyOn=False)
    class Meta:
        model = PublicProfile
        fields = ['profile']

base/views.py
from turtle import update
from django.conf import Settings
from django.dispatch import receiver
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import CreateUserForm, SettingsForm, PurchaseForm
from .forms import MessageForm,ProfileForm
from .models import Message
from .models import Profile
from .models import StoreItem
from .models import PurchaseItem
from django.core.mail import send_mail
from django.core.files.storage import FileSystemStorage
from datetime import datetime
import re
# 10 Points: 😊🤩👏🥰❤️🌈🌹🌻☀️🙌🌟
# 20 Points:✨🏅💖🍨🍕🎈🐶🐱🐸💫
# 50 Points: 💎👑💛
# 100 Points: 💯
EMOJIS = {"😊":10,"👏" : 10, "🤩" : 10,"❤️": 10, "🌈" : 10, "🙌":10,"🌟":10,"💫":20, 
"🥰":10,"🏅":20,"🎈":20,"💖":20,"👑":50,"🐶":20,"💛" : 50,"✨":20,
"🐱":20,"🐸":20,"🌹":20,"🌻":10,"☀️":10,"🍨":20,"🍕":20,"💎":50,"💯":100}

def loginPage(request):
    # specify page
    page = 'login'

    # if user is already logged in, redirect to home
    if request.user.is_authenticated:
        return redirect('home')

    if request.method == 'POST':
        username = request.POST.get('username').lower()
        password = request.POST.get('password')

        # if user exists, grab them, otherwise, send error that user does not exist
        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'User does not exist')

        user = authenticate(request, username=username, password=password)

        # if user exists and is authenticated, log them in and redirect them to the home page, otherwise, specify username or
        # password doesn't exist
        if user is not None:
            login(request, user)
            print(user.email)
            return redirect('home')
        else:
            messages.error(request, 'Username or password does not exist')
    context = {'page': page}
    return render(request, 'base/login_register.html', context)

def logoutUser(request):
    logout(request)
    return redirect('home')

def registerPage(request):
    form = CreateUserForm()

    # if the request is a post, make sure the registrationform is valid, update the user email if it was changed, 
    # log the user in, and redirect them to the home page
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.email = user.email.lower()
            user.save()
            Profile.objects.create(
                user=user,
                email = user.email
            )
            login(request, user)
            return redirect('home')
        # otherwise, send error message that an error occurred during registration
        else:
            messages.error(request, 'An error occured during registration')

    return render(request, 'base/login_register.html', {'form': form})

def home(request):
    page = 'Home'

    # if username isn't blank, grab user object, otherwise, render home without user
    if(request.user.username is not ''):
        user = User.objects.get(username=request.user.username)
    else:
        context = {'page': page}
        return render(request, 'base/home.html', context)

    # grab messages send to user and send them to frontend to be displayed, allowing for them to be filtered by sender
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    messages_to = user.receiver.all()
    messages_to = messages_to.filter( 
        Q(sender__username__icontains=q)
        )
    message_count = messages_to.count()

    unique_senders = user.receiver.all()
    senders = []

    now = datetime.now()
    timeTillMidnight = (now.replace(hour=0, minute=0, second=0, microsecond=0) - now)
    timeTillMidnight = str(timeTillMidnight)
    print(timeTillMidnight)
    match = re.search(r'[0-9]*\:[0-9]*', timeTillMidnight)
    timeTillMidnight = match.group
    print(timeTillMidnight)

    # create list of unique senders to be sent to the frontend so messages can be filtered by sender
    for message in unique_senders:
        if message.sender not in senders:
            senders.append(message.sender)

    context = {'message_count': message_count, 'messages_to': messages_to, 'senders': senders,'page': page, 'timeTillMidnight': timeTillMidnight}
    return render(request, 'base/home.html', context)

def getPoints(message):
    chars = list(message)
    pointTotal = 0

    # iterate through the message's body, totaling the number of points in the message based on emojis
    for char in chars:
        if char in EMOJIS.keys():
            pointTotal += EMOJIS[char]
            print(char + " : pointTotal " + str(pointTotal))
    return pointTotal

def message(request, pk):
    message = Message.objects.get(id=pk)
    context = {'message': message}
    return render(request, 'base/message.html', context)
def updatePoints(senderName,recieverName,pointTotal):
    sender = Profile.objects.get(user=senderName.id)
    reciever = Profile.objects.get(user=recieverName.id)

    # check not sending to themselves
    if sender.id == reciever.id:
        error = "Error cannot send message to yourself"
        print(error)
        return error

    # check sender has enough points
    if sender.pointsToSend < pointTotal:
        error = "Error not enough sender points!"
        print(error)
        return error

    # decrement sender points
    print("Sender " + senderName.username + " spent " + str(pointTotal) + " sender points")
    print("Sender points before " +  str(sender.pointsToSend))
    sender.pointsToSend = sender.pointsToSend - pointTotal
    print("Sender points after " +  str(sender.pointsToSend))
    # increment reciever points 
    print("Reciever " + recieverName.username + " recieved " + str(pointTotal) + " points")
    print("Reciever points before " +  str(reciever.pointsReceived))
    reciever.pointsReceived = reciever.pointsReceived + pointTotal
    print("Reciever points after " +  str(reciever.pointsReceived))
    sender.save()
    reciever.save()
    return ""
@login_required(login_url='login')
def createMessage(request):
    user = request.user
    page = 'Messages'
    form = MessageForm()
    validReceivers  = User.objects.filter(~Q(username=request.user.username))
    error = ""
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            obj = form.save(commit = False)
            obj.sender = request.user
            # get points for emojis in the message
            pointTotal = getPoints(obj.body)
            obj.pointTotal = pointTotal

            # decrement sender points and increment reciever points
            success = updatePoints(obj.sender,obj.receiver, pointTotal)          
            if success == "":
                obj.save()
                return redirect('home')
            else: 
                error = success
    context = {'form': form,'validReceivers':validReceivers,'error':error, 'page': page, 'user': user}
    return render(request, 'base/message_form.html', context)

def purchaseItem(item,profile):
    # if the user doesn't have enough points, send error saying that
    if profile.pointsReceived < item.cost:
        error = "Error not enough points!"
        print("Error not enough points!")
        return error
    profile.pointsReceived = profile.pointsReceived- item.cost
    profile.save()
    item.timesPurchased = item.timesPurchased + 1
    item.save()
    # otherwise, purchase item, updating the points and times purchased accordingly and sending confirmation message back
    message = "Successfully purchased " + str(item.name) + " for " + str(item.cost)
    print(message)
    return message
 
def addStoreItem(name, cost):
    newItem = StoreItem.objects.create(name=name,cost=20)
    newItem.save()
def editStoreImage(item,image):
    results = StoreItem.objects.filter(name=item)
    newItem = results[0]
    newItem.image = image
    newItem.save()
@login_required(login_url='login')
def store(request):
    page = "Store"
    form = PurchaseForm()
    storeItems = StoreItem.objects.all()
    userItems = PurchaseItem.objects.filter(user=request.user.id)

    # populate map of most recently purchased items and who has purchased 
    itemRecentBuyers = {}

    # purchased items in order of creation
    purchasedAll = PurchaseItem.objects.all()
    for purchased in purchasedAll:
        profile = Profile.objects.get(user=purchased.user.id)
        if profile.privacyOn is False:
            if purchased.item.id in itemRecentBuyers:
                buyers = itemRecentBuyers[purchased.item.id]
                if purchased.user.username not in buyers:
                    buyers.append(purchased.user.username)
                    itemRecentBuyers[purchased.item.id] = buyers
            else:
                itemRecentBuyers[purchased.item.id] = [purchased.user.username]
            print(itemRecentBuyers[purchased.item.id])
    print(str(itemRecentBuyers))
        
    currProf = Profile.objects.get(user=request.user.id)
    userPoints = currProf.pointsReceived
    if request.method == 'POST':
        form = PurchaseForm(request.POST)
        if form.is_valid():
            obj = form.save(commit = False)
            obj.user = request.user
            currProf = Profile.objects.get(user=request.user.id)
            # purchase
            success = PurchaseItem.purchase(obj.item,currProf)          
            if success:
                obj.save()
                return redirect('home')
            else:
                # print error message
                print("error purchase failed")
                return redirect('home')
        else:

base/templates/base/delete.html
{% extends 'main.html' %}

{% block content %}

<form method = "POST" action="">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{obj}}"?</p>
    
    <a href="{{request.META.HTTP_REFERER}}">Go Back</a>
    <input type = "submit" value = "Confirm" />
</form>

{% endblock content %}

base/templates/base/login_register.html
{% if page == 'login' %}

<style>
    body{
        margin: 0px;
    }
    .login-container{
        display: flex;
        height: 100vh;
        

    }
    .left{
        width: 50vw;
        background-image: linear-gradient(to right, #008F97, #6EBFB6);
        display: flex;
        justify-content: center;
        align-items: center;   
    }

    .right{
        width: 50vw;
        background: white;
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
         
    }
    .message{
        font-weight: 550;
        font-size: 8vw;
        color: white;
        font: sans-serif;
        text-align: left;
    }

    loginLogo{
        color: black;
        font: sans-serif;
        font-size: 30px;
        text-align: left;
        margin: 10px;
    }
    .middle{
        width: 9vw;
        background: pink;
        display: flex;
        justify-content: center;
        align-items: center; 
    }
    .line1{
        width: 3vw;
        height: 100vh;
        background: #ED3E4B;
        display: flex;
    }
    .line2{
        width: 3vw;
        height: 100vh;
        background: #E98D20;
        display: flex;
        
    }
    .line3{
        width: 3vw;
        height: 100vh;
        background: #FED760;
        display: flex;
        
    }

    .username{
        display: flex;
        font-size: 17px;
        align-items: left;
        justify-content: center;
        margin: 20px;
        flex-direction: column;
    }
    .password{
        display: flex;
        font-size: 17px;
        align-items: left;
        justify-content: center;
        margin: 20px;
        flex-direction: column;
    }
    submit{
        position: fixed;
        top: 500px;
        left:1000px;
        font-size: 20px;
    }
    .submitLogin{
        display: flex;
        font-size: 20px;
        align-items: center;
        margin: 20px;
    }
    .registerButton{
        display: flex;
        font-size: 15px;
        align-items: center;
        justify-content: center;
    }

    

</style>

<body>
    <div class = "login-container">
        <div class= "left">
            <div class = "message">
                Start<br> spreading <br> some<br> positivity 
            </div>
        </div>
        <div class="middle">
            <div class="line1"></div>
            <div class="line2"></div>
            <div class="line3"></div>
        </div>
        <div class = "right"> 
            <loginLogo>
                <h1 style="color:black" style="font-family: sans-serif">4positivity</h1>
            </loginLogo>

                
                    <form method="POST" action="">
                        {% csrf_token %}
                        <div class= "username">
                            <label for="username">Username</label>
                            <input type="text" name="username" placeholder="ex. janeDoe1" style="width: 250px; padding: 5px;"/>
                        </div>

                        <div class= "password">
                            <label for="username">Password</label>
                            <input type="password" name="password" style="width: 250px; padding: 5px;"/>
                        </div>
                        <div class= "submitLogin">
                                <input type="submit" value="Login" style="padding: 5px 50px; width: 250px; background-color: #6EBFB6; color: white; border-radius: 10px; border-color: #6EBFB6"/>
                        </div>

                        <div class = "registerButton">
                        <a href="{% url 'register' %}">Create Account</a>
                        </div>

                        
                    </form>
                
        </div>
        
        

    </div>
</body>

{% else %}

<style>
    body{
        margin: 0px;
    }
    .login-container{
        display: flex;
        height: 100vh;
        

    }
    .left{
        width: 50vw;
        background-image: linear-gradient(to right, #008F97, #6EBFB6);
        display: flex;
        justify-content: center;
        align-items: center;   
    }
    .middle{
        width: 9vw;
        background: pink;
        display: flex;
        justify-content: center;
        align-items: center; 
    }
    .line1{
        width: 3vw;
        height: 100vh;
        background: #ED3E4B;
        display: flex;
    }
    .line2{
        width: 3vw;
        height: 100vh;
        background: #E98D20;
        display: flex;
        
    }
    .line3{
        width: 3vw;
        height: 100vh;
        background: #FED760;
        display: flex;
        
    }

    .right{
        width: 50vw;
        background: white;
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
    }
    .message{
        font-weight: 550;
        font-size: 8vw;
        color: white;
        font: sans-serif;
        text-align: left;
    }

    loginLogo{
        color: black;
        font: sans-serif;
        font-size: 30px;
        text-align: left;
        margin: 10px;
    }

    .username{
        display: flex;
        font-size: 17px;
        align-items: left;
        justify-content: center;
        margin: 20px;
        flex-direction: column;
    }

    .centerText{
        display: flex;
        font-size: 15px;
        align-items: left;
        justify-content: center;
        flex-direction: column;
    }

    .email{
        display: flex;
        font-size: 17px;
        align-items: left;
        justify-content: center;
        margin: 20px;
        flex-direction: column;
    }

    .password{
        display: flex;
        font-size: 17px;
        align-items: left;
        justify-content: center;
        margin: 20px;
        flex-direction: column;
    }

    .submitLogin{
        display: flex;
        font-size: 20px;
        align-items: center;
        justify-content: center;
        margin: 20px;
        flex-direction: column;
    }
    .registerButton{
        display: flex;
        font-size: 15px;
        align-items: center;
        justify-content: center;
    }

    
</style>

<body>
    <div class = "login-container">
        <div class= "left">
            <div class= "message">
                Start<br> spreading <br> some<br> positivity 
            </div>
        </div>
        <div class="middle">
            <div class="line1"></div>
            <div class="line2"></div>
            <div class="line3"></div>
        </div>
        <div class = "right">
            <loginLogo>
                <h1 style="color:black" style="font-family: sans-serif">4positivity</h1>
            </loginLogo>
            <div>
                <form method="POST" action="">
                        {% csrf_token %}
                    <div>
                        <form method="POST" action="">
                    <div class = "username">
                        <label for="username">Username</label>
                        <input type="text" placeholder = "ex. janeDoe1" name="username" maxlength="150" autofocus required id="id_username" style = "width: 300px; padding: 5px;">
                    </div> 
                    <div class = "centerText">
                        <span class="helptext"><li>Required.</li><li> 150 characters or fewer.</li><li> Letters, digits and @/./+/-/_ only.</li></span>
                    </div>
                        
                    

                    
                    <div class = "email">
                        <label for="email">Email Address</label>
                        <input type="email" name="email" maxlength="254" id="id_email" style = "width: 300px; padding: 5px;" placeholder = "ex. janeDoe12@gmail.com">
                    </div>

                    
                    <div class = "password">
                        <label for="password">Password</label>
                        <input type="password" name="password1" autocomplete="new-password" required id="id_password1" style = "width: 300px; padding: 5px;">
                    </div>   
                    <div class = "centerText">
                        <span class="helptext"><li>Your password can’t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can’t be a commonly used password.</li><li>Your password can’t be entirely numeric.</li></ul></span>
                    </div>

                    
                    <div class = "password">
                        <label for="password2">Password Confirmation</label>
                        <input type="password" name="password2" autocomplete="new-password" required id="id_password2", style = "width: 300px; padding: 5px;" >
                    </div>   
                    
                    <div class = "submitLogin">
                        <input type="submit" value="Register" style="padding: 5px 50px; width: 200px; background-color: #6EBFB6; color: white; border-radius: 10px; border-color: #6EBFB6"/>
                    </div>

                </form>
                    
                    <div class = "registerButton">
                    <a href="/login/">Already Signed Up?</a>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
</body>




{% endif %}

base/templates/base/message.html
{% extends 'main.html' %}

{% block content %}
<h1>{{message.sender.username}}</h1>

{% endblock content %}

base/templates/base/settings.html
{% extends 'main.html' %} {% block content %}
<style>
    * {
        margin: 0;
        border: 0;
        padding: 0;
    }
    
    .containerSet {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        padding: 20px;
        margin: 20px;
    }
    
    .itemSet {
        height: 40px;
        margin-bottom: 10px;
    }
    
    .headerL {
        display: fixed;
        background: #E98D20;
        height: 5px;
        width: 60%;
        margin: auto;
    }
</style>
<p>{{settings}}</p>
<br>
<div class="headerL"></div>
<!-- change settings form -->
<div class="containerSet">
    <form method="POST" action="" , enctype="multipart/form-data">
        {% csrf_token %} {{form.as_p}}

        <div class="itemSet">
            <br>
            <input type="submit" value="Update Settings " style="color: white; border-radius: 12px; background-color: #E98D20; height: 40px; width: 100px;" />
        </div>

    </form>
</div>
<br>
<div class="headerL"></div>

{% endblock content %}

base/templates/base/store.html
{% extends 'main.html' %}{% block content %}
<style>
    *{
        margin: 0; border: 0; padding: 0; 
    }

    .store-container {
        display: flex;
        min-height: calc(100vh - 100px)
    }

    .sidebar {
        display: flex;
        min-width: 300px;
        max-width: 300px;
        max-height: 100vh;
        overflow: auto;
        background-color: #E5E5E5;
        align-items: center;
        flex-direction: column;
        

    }

    .content{
        display: flex;
        flex-grow: 1;
        flex-direction: column;
        max-height: 100vh;
        overflow: auto;
       
        
        
    }

    .sidebar heading{
        font-weight: 100;
        font-size: 3.5vw;
        color: black;
        font: sans-serif;
        text-align: center; 
    }

    .sidebar space{
        min-height: 50px;
        display: flex;
    }
    
    .content header{
        min-height: 7vh;
        font-weight: 100;
        font-size: 2.5vw;
        color: black;
        font: sans-serif;
        text-align: right; 
        margin: 20px;
        border-bottom: 1px solid black;
    }

    .products {
        display: flex;
        flex-wrap: wrap;
        flex-direction: row;
      }
    .purchaseFrame {
        display: flex;
        flex-direction: column;
        
      }

    .product-card {
        padding: 1%;
        margin: 2.5%;
        flex-grow: 1;
        flex-basis: 25%;
        display: flex;
        border: 1px solid #FED760;
        align-items: center;
        justify-content: center;
        flex-wrap: wrap;
        flex-direction: column;
        background-color: #FED760;
        border-radius: 20px;

      }
      .purchased-card {
        padding: 1%;
        margin: 5%;
        flex-grow: 1;
        flex-basis: 25%;
        display: flex;
        border: 1px solid #E98D20;
        align-items: center;
        justify-content: center;
        flex-wrap: wrap;
        flex-direction: column;
        background-color: #E98D20;
        border-radius: 20px;

      }

    .product-image img {
        max-width: 100%;
      }
    .product-info {
        margin-top: auto;
      }

    .purchase{
        display: flex;
        flex-wrap: wrap;
        flex-direction: column;
        background-color: white;
        min-height: 10vh;
    }

    .selectItem{
        display: flex;
        align-items: right;
        justify-content: right;
        margin: 15px;
    }

    .buyButton{
        display: flex;
        align-items: right;
        justify-content: right;
        margin: 15px;
    }

    
      


</style>

<div class = "store-container">
    <aside class ="sidebar">
        <space></space>
        <heading>Recently<br> Purchased</heading>
        <section class="purchaseFrame">
            {% for purchasedItem in userItems %}
                <div class="purchased-card">
                    <div class="product-image">
                        {% load static %}
                        <img src="{% static purchasedItem.item.image %}" alt="My image" style ="height: 20vh; width: 15vw;">
                    </div>
                    <div class="product-info">
                        {{purchasedItem.item}}
                        <p style="color:black;">Cost: {{purchasedItem.item.cost}}</p>
                    </div>
                
                </div>
            {% endfor %}
            
        </section>
    </aside>
    <main class = "content">
        <header> {{userPoints}} Positivity Points</header>
        
        <section class="products">
            {% for item in storeItems %}
                
                <div class="product-card">
                    <div class="product-image">
                        {% load static %}
                        <img src="{% static item.image %}" alt="My image" style ="height: 20vh; width: 15vw;">
                    </div>
                    <div class="product-info">
                        {{item}}
                        <p style="color:black;">Cost: {{item.cost}}</p>
                        {% load template_filters %}
                        <p style="color:black;">{{ itemRecentBuyers|get_item:item.id }}</p>
                    </div>
                
                </div>
            {% endfor %}
            
        </section>

        <div class= "purchase">
        <form method="POST" action="">
            {% csrf_token %}
            <!-- <input type="hidden" name="csrfmiddlewaretoken" value="zk1hegiuYd8b2yNmHdt7dHIUGpU4EcqWAwoy4a9q8yCTb8eb5hE4B31TmcGEE7Nf"> -->
            <div class= "selectItem">
                    <label for="id_item" style="font-size: 20px; font-weight: 100;">Item:</label>
                    <select name="item" required="" id="id_item" style= "height: 3vh; border: 1px solid black;">
                <option value="" selected="">---------</option>
                
                <option value="1">CowboyHat</option>
                
                <option value="3">boot</option>
                
                <option value="4">Daisy</option>
                
                <option value="5">Disco Ball</option>
                
                <option value="6">Ghost</option>
                
                <option value="7">Orange Smile</option>
                
                <option value="8">Purple Smile</option>
                
                <option value="9">Red Smile</option>
                
                <option value="10">World</option>
                
                </select>
                
            </div>   
                  
                
            <div class = "buyButton">
           
            <input type="submit" value="Buy" style="min-width: 15vw; min-height: 3vh; color: white; border-radius: 70px; background-color: #E98D20;"/>
            </div>
        </div>
        </form>
        
    </main>
</div>


{% endblock content %}